[package]
name = "remap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "1.3.0"
input-linux = "0.6.0"
# notify-rust = "4.5.10"
